services:
  excalidraw:
    image: "excalidraw/excalidraw:latest"
    ports:
      - 5000:80

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /sonarr/data:/config
      - /sonarr/tvseries:/tv #optional
      - /sonarr/downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  
