add_newline = true
format = "$username $hostname  $directory $golang $rust $python $git_branch $git_status\n $character"

[character]
error_symbol = "[ 󰅙 ](bold fg:#f38ba8)"
success_symbol = "[  ](bold fg:#cba6f7)"

[username]
format = "[   $user](bg:default fg:#a6e3a1)[ @](bg:default fg:#f38ba8)"
show_always = true
style_root = "bg:default fg:#f38ba8"
style_user = "bg:default fg:#cdd6f4"

[hostname]
disabled = false
format = "[$hostname](bg:default fg:#cba6f7)"
ssh_only = false
trim_at = ".companyname.com"

[directory]
format = "([  ](bg:default fg:#f38ba8) [$path ]($style))"
style = "bg:default fg:default"
home_symbol = "  "
read_only = "  "
truncation_length = 6
truncation_symbol = "••/"

[golang]
format = "[$symbol]($style)  [$version](fg:red)"
style = "bg:default fg:default"
symbol = ""

[rust]
format = "[$symbol]($style)  [$version](fg:red)"
style = "bg:default fg:default"
symbol = ""

[python]
format = '[[$symbol](fg:#f5c2e7)  ([$version](fg:red)) ([$virtualenv](fg:#a6e3a1))]($style)'
style = "bg:default fg:default"
symbol = "󰌠"

[git_branch]
format = "[$symbol $branch ](fg:purple)(:$remote_branch)"
style = "bold green"
symbol = "󰘬"
truncation_length = 10
truncation_symbol = "…/"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold green"
ahead = " ↑${count} "
behind = " ↓${count} "
conflicted = " C "
deleted = "[ D-$count ](fg:red)"
diverged = " ↕ ↑${ahead_count} ↓${behind_count} "
modified = "[ M-${count}](fg:red)"
renamed = "R-${count}"
staged = "[ M-${count}](fg:green)"
stashed = "[ T-${count} ]"
untracked = " U "
up_to_date = " ✓ "
